version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: social-nginx
    ports:
      - '80:80'
    volumes:
      - ./php:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - social-auth

  php:
    build:
      context: ./php
      dockerfile: ../Docker/php/Dockerfile
    container_name: social-php
    volumes:
      - ./php:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - social-auth

  composer:
    image: composer:latest
    container_name: social-composer
    volumes:
      - ./php:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - social-auth

  mysql:
    image: mysql:5.7
    container_name: social-mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - social-auth-data:/var/lib/mysql
    networks:
      - social-auth

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: social-admin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - '8880:80'
    links:
      - mysql
    networks:
      - social-auth

  mailcatcher:
    container_name: social-mailcatcher
    build:
      context: ./Docker/Mailcatcher
      dockerfile: Dockerfile
    ports:
      - '1025:1025'
      - '1080:1080'
    networks:
      - social-auth

networks:
  social-auth:

volumes:
  social-auth-data:
