default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  pool: 5
  username: user
  password: password

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
